// System Design Oracle — website. Same content and reading layers as the Mac app.
// content.json is generated by scripts/build_site.py from Sources/SystemDesignOracle/Content.

const REPO_URL = "https://github.com/amalmehta/SystemDesignOracle";

// Sidebar order, roughly bottom of the stack to the top (matches Library.swift).
const DOMAIN_ORDER = [
  "os", "gpu", "storage", "networking", "distributed", "data",
  "security", "ml-training", "inference", "autonomous-vehicles",
];

const LAYERS = [
  { n: 1, name: "The Gist", blurb: "One sentence. The idea in a breath.", color: "var(--l1)" },
  { n: 2, name: "The Picture", blurb: "Plain English and a diagram.", color: "var(--l2)" },
  { n: 3, name: "How It Works", problemName: "The Design", blurb: "Components, flow, trade-offs, real numbers.", color: "var(--l3)" },
  { n: 4, name: "Expert Depth", blurb: "Failure modes, real systems, interview questions.", color: "var(--l4)" },
];
const layerName = (n, forProblem) => (forProblem && LAYERS[n - 1].problemName) || LAYERS[n - 1].name;

// SF Symbols names in the content, shown as emoji on the web.
const SYMBOLS = {
  "terminal": "⌨️", "cpu": "🔲", "externaldrive": "💽", "antenna.radiowaves.left.and.right": "📡",
  "network": "🕸️", "cylinder.split.1x2": "🗄️", "lock.shield": "🛡️", "brain": "🧠",
  "bolt.horizontal": "⚡", "car": "🚗",
};

const state = {
  domains: [],
  problems: [],
  topics: new Map(),        // id -> topic
  topicDomain: new Map(),   // topic id -> domain
  haystack: new Map(),      // "topic:id" / "problem:id" -> lowercased text
  depth: readDepth(),
  query: "",
  collapsed: new Set(),
  history: [],
  current: null,            // route string
};

// ---------- Utilities ----------

function storageGet(key) { try { return localStorage.getItem(key); } catch { return null; } }
function storageSet(key, value) { try { localStorage.setItem(key, value); } catch { /* private mode */ } }
function readDepth() {
  const d = parseInt(storageGet("depth"), 10);
  return d >= 1 && d <= 4 ? d : 2;
}

const escapeHTML = (s) => String(s).replace(/[&<>"']/g, (c) =>
  ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

// Inline markdown: `code`, **bold**, *italic*. "~" means "approximately", never strikethrough.
function md(s) {
  const parts = String(s).split(/(`[^`]*`)/);
  return parts.map((part) => {
    if (part.startsWith("`") && part.endsWith("`") && part.length > 1) {
      return `<code>${escapeHTML(part.slice(1, -1))}</code>`;
    }
    return escapeHTML(part)
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/(^|[^*\w])\*(?!\s)(.+?)(?<!\s)\*(?!\w)/g, "$1<em>$2</em>");
  }).join("");
}

function allStrings(value, out = []) {
  if (typeof value === "string") out.push(value);
  else if (Array.isArray(value)) value.forEach((v) => allStrings(v, out));
  else if (value && typeof value === "object") Object.values(value).forEach((v) => allStrings(v, out));
  return out;
}

function matches(key, query) {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (!words.length) return true;
  const text = state.haystack.get(key) || "";
  return words.every((w) => text.includes(w));
}

const rank = (id) => { const i = DOMAIN_ORDER.indexOf(id); return i === -1 ? 999 : i; };
const domainSymbol = (d) => SYMBOLS[d.symbol] || "•";

// ---------- Loading ----------

async function load() {
  const res = await fetch("content.json");
  if (!res.ok) throw new Error(`content.json: HTTP ${res.status}`);
  const data = await res.json();
  state.domains = data.domains.sort((a, b) => rank(a.id) - rank(b.id) || a.name.localeCompare(b.name));
  state.problems = data.problems.sort((a, b) => rank(a.domain) - rank(b.domain) || a.title.localeCompare(b.title));
  for (const d of state.domains) {
    for (const t of d.topics) {
      state.topics.set(t.id, t);
      state.topicDomain.set(t.id, d);
      state.haystack.set(`topic:${t.id}`, (allStrings(t).join(" ") + " " + d.name).toLowerCase());
    }
  }
  for (const p of state.problems) {
    state.haystack.set(`problem:${p.id}`, allStrings(p).join(" ").toLowerCase());
  }
}

// ---------- Rendering helpers ----------

const layerHeader = (n, forProblem) => `
  <div class="layer-header">
    <span class="badge" style="background:${LAYERS[n - 1].color}">${n}</span>
    <h2>${layerName(n, forProblem)}</h2>
  </div>`;

const sub = (title) => `<div class="sub">${escapeHTML(title)}</div>`;
const paragraphs = (ps) => ps.map((p) => `<p>${md(p)}</p>`).join("");
const bullets = (items, numbered) =>
  `<${numbered ? "ol" : "ul"} class="bullets">${items.map((i) => `<li>${md(i)}</li>`).join("")}</${numbered ? "ol" : "ul"}>`;
const namedCards = (items) =>
  `<div class="cards">${items.map(([name, text]) => `<div class="card"><h3>${md(name)}</h3><p>${md(text)}</p></div>`).join("")}</div>`;
const numbersGrid = (numbers) =>
  `<div class="cards">${numbers.map((n) => `<div class="card number"><div class="value">${md(n.value)}</div><div class="metric">${md(n.metric)}</div></div>`).join("")}</div>`;

function tradeoffTable(tradeoffs) {
  return `<div class="table-wrap"><table class="tradeoffs">
    <thead><tr><th>Choice</th><th class="gain">＋ Gain</th><th class="cost">− Cost</th></tr></thead>
    <tbody>${tradeoffs.map((t) => `<tr><td><strong>${md(t.choice)}</strong></td><td>${md(t.pro)}</td><td>${md(t.con)}</td></tr>`).join("")}</tbody>
  </table></div>`;
}

function diagram(d, tint) {
  const steps = d.steps.map((s, i) => `
    <div class="step-wrap">
      <div class="step"><b>${escapeHTML(s.label)}</b><span>${escapeHTML(s.detail)}</span></div>
      ${i < d.steps.length - 1 ? '<span class="arrow" aria-hidden="true">→</span>' : ""}
    </div>`).join("");
  return `<figure class="diagram" style="--tint:${tint}"><div class="flow">${steps}</div>
    <figcaption class="caption">${md(d.caption)}</figcaption></figure>`;
}

// Interview questions with the answer hidden until asked for — try it yourself first.
function questions(qs) {
  return qs.map((q) => `
    <div class="card question">
      <div class="q">${md(q.q)}</div>
      <button class="link-btn" data-reveal>Show answer</button>
      <div class="a" hidden>${md(q.a)}</div>
    </div>`).join("");
}

function goDeeper(forProblem) {
  if (state.depth >= 4) return "";
  const next = LAYERS[state.depth];
  return `<button class="deeper" data-depth-set="${next.n}" style="--tint:${next.color}">
    <span>↓</span><b>Go deeper: ${layerName(next.n, forProblem)}</b><span class="muted">— ${next.blurb}</span></button>`;
}

function relatedChips(ids) {
  return `<div class="chips">${ids.map((id) => {
    const t = state.topics.get(id), d = state.topicDomain.get(id);
    if (!t) return "";
    return `<a class="chip" href="#/topic/${id}" title="${escapeHTML(d.name + ": " + t.gist)}">${domainSymbol(d)} ${escapeHTML(t.title)}</a>`;
  }).join("")}</div>`;
}

// ---------- Pages ----------

function renderHome() {
  const topicCount = state.topics.size;
  return `<div class="column">
    <h1>System Design Oracle</h1>
    <p class="lede">How real systems are built, from the kernel to the self-driving car — ${state.domains.length} domains, ${topicCount} topics and ${state.problems.length} worked design problems.</p>
    ${sub("Every page reads in four layers — stop whenever you’ve had enough")}
    <div class="layers">${LAYERS.map((l) => `
      <div class="layer-card" style="--tint:${l.color}"><b>${l.n}&nbsp; ${l.name}</b><span>${l.blurb}</span></div>`).join("")}
    </div>
    <p class="muted small" style="margin-top:8px">Set the depth at the top right, or press 1–4.</p>
    ${sub("Design problems — worked end to end")}
    <div class="cards">${state.problems.map((p) => `
      <a class="card" href="#/problem/${p.id}"><h3>${escapeHTML(p.title)}</h3><p class="clamp">${escapeHTML(p.prompt)}</p></a>`).join("")}
    </div>
    ${sub("Concepts by domain")}
    <div class="cards">${state.domains.map((d) => `
      <div class="card domain-card"><h3>${domainSymbol(d)} ${escapeHTML(d.name)}</h3><p>${md(d.summary)}</p>
        <ul>${d.topics.map((t) => `<li><a href="#/topic/${t.id}">${escapeHTML(t.title)}</a></li>`).join("")}</ul></div>`).join("")}
    </div>
  </div>`;
}

function renderTopic(t) {
  const d = state.topicDomain.get(t.id), depth = state.depth;
  let html = `<div class="column">
    <div class="eyebrow">${domainSymbol(d)} ${escapeHTML(d.name)}</div>
    <h1>${escapeHTML(t.title)}</h1>
    ${layerHeader(1)}<p class="gist">${md(t.gist)}</p>`;
  if (depth >= 2) {
    html += layerHeader(2) + paragraphs(t.overview) + diagram(t.diagram, "var(--l2)");
  }
  if (depth >= 3) {
    const h = t.howItWorks;
    html += layerHeader(3)
      + sub("The parts") + namedCards(h.components.map((c) => [c.name, c.role]))
      + sub("Step by step") + bullets(h.flow, true)
      + sub("Trade-offs") + tradeoffTable(h.tradeoffs)
      + sub("Numbers to know") + numbersGrid(h.numbers);
  }
  if (depth >= 4) {
    const e = t.expert;
    html += layerHeader(4) + paragraphs(e.details)
      + sub("How it breaks") + namedCards(e.failureModes.map((f) => [f.name, f.description]))
      + sub("In real systems") + namedCards(e.realSystems.map((r) => [r.name, r.note]))
      + sub("Test yourself") + questions(e.questions);
  }
  html += goDeeper(false);
  const usedIn = state.problems.filter((p) => p.related.includes(t.id));
  if (usedIn.length) {
    html += `<div style="margin-top:20px">${sub("Used in design problems")}</div><div class="problem-links">`
      + usedIn.map((p) => `<a href="#/problem/${p.id}">🔨 ${escapeHTML(p.title)}</a>`).join("") + "</div>";
  }
  html += sub("Related topics") + relatedChips(t.related) + "</div>";
  return html;
}

function renderProblem(p) {
  const d = state.domains.find((x) => x.id === p.domain), depth = state.depth;
  let html = `<div class="column">
    <div class="eyebrow">🔨 Design Problem · ${escapeHTML(d ? d.name : p.domain)}</div>
    <h1>${escapeHTML(p.title)}</h1>
    <div class="prompt">${md(p.prompt)}</div>
    ${layerHeader(1, true)}<p class="gist">${md(p.gist)}</p>`;
  if (depth >= 2) {
    html += layerHeader(2, true) + paragraphs(p.overview) + diagram(p.diagram, "var(--problem)");
  }
  if (depth >= 3) {
    const r = p.requirements;
    html += layerHeader(3, true)
      + sub("What it must do") + bullets(r.functional)
      + sub("How well it must do it") + bullets(r.nonFunctional)
      + sub("Back of the envelope") + numbersGrid(r.estimates)
      + p.stages.map((s, i) => `
        <section class="stage">
          <div class="stage-head"><span class="stage-num">${i + 1}</span><h3>${escapeHTML(s.name)}</h3></div>
          <p class="stage-summary">${md(s.summary)}</p>
          ${bullets(s.points)}
          ${depth >= 4 ? `<div class="deep"><div class="deep-label">↧ Deep dive</div>${paragraphs(s.deepDive)}</div>` : ""}
        </section>`).join("")
      + sub("Trade-offs") + tradeoffTable(p.tradeoffs);
  }
  if (depth >= 4) {
    const e = p.expert;
    html += layerHeader(4, true) + `<p class="muted">Each stage above now includes its deep dive.</p>`
      + sub("How it breaks") + namedCards(e.failureModes.map((f) => [f.name, f.description]))
      + sub("In real systems") + namedCards(e.realSystems.map((r) => [r.name, r.note]))
      + sub("Interviewer follow-ups") + questions(e.questions);
  }
  html += goDeeper(true) + `<div style="margin-top:20px">${sub("Concepts used")}</div>` + relatedChips(p.related) + "</div>";
  return html;
}

// ---------- Sidebar ----------

function renderNav() {
  const q = state.query, route = state.current;
  const link = (href, label, key) =>
    `<a href="${href}" class="${route === key ? "active" : ""}">${label}</a>`;
  const section = (id, title, links) => {
    const open = q || !state.collapsed.has(id);
    return `<details class="nav-section" data-section="${id}" ${open ? "open" : ""}>
      <summary>${title}</summary>${links}</details>`;
  };
  let html = "", any = false;
  const problems = state.problems.filter((p) => matches(`problem:${p.id}`, q));
  if (problems.length) {
    any = true;
    html += section("problems", "Design Problems",
      problems.map((p) => link(`#/problem/${p.id}`, `🔨 ${escapeHTML(p.title)}`, `problem/${p.id}`)).join(""));
  }
  for (const d of state.domains) {
    const topics = d.topics.filter((t) => matches(`topic:${t.id}`, q));
    if (!topics.length) continue;
    any = true;
    html += section(d.id, `${domainSymbol(d)} ${escapeHTML(d.name)}`,
      topics.map((t) => link(`#/topic/${t.id}`, escapeHTML(t.title), `topic/${t.id}`)).join(""));
  }
  if (!any) html = `<div class="empty">Nothing matches “${escapeHTML(q)}”</div>`;
  document.getElementById("nav").innerHTML = html;
}

// ---------- Routing ----------

function parseRoute() {
  const m = location.hash.match(/^#\/(topic|problem)\/([\w-]+)$/);
  return m ? `${m[1]}/${m[2]}` : "";
}

function render({ keepScroll = false } = {}) {
  const route = parseRoute();
  const content = document.getElementById("content");
  const [kind, id] = route.split("/");
  let html, title = "System Design Oracle";
  if (kind === "topic" && state.topics.has(id)) {
    const t = state.topics.get(id); html = renderTopic(t); title = t.title;
  } else if (kind === "problem" && state.problems.some((p) => p.id === id)) {
    const p = state.problems.find((x) => x.id === id); html = renderProblem(p); title = p.title;
  } else {
    html = renderHome();
  }
  const scroll = content.scrollTop;
  content.innerHTML = html;
  content.scrollTop = keepScroll ? scroll : 0;
  document.getElementById("toolbar-title").textContent = title;
  document.title = title === "System Design Oracle" ? title : `${title} · System Design Oracle`;
  state.current = route;
  renderNav();
  document.querySelectorAll(".depth button").forEach((b) =>
    b.setAttribute("aria-checked", String(Number(b.dataset.depth) === state.depth)));
  document.getElementById("back-btn").disabled = state.history.length === 0;
}

function setDepth(n) {
  state.depth = n;
  storageSet("depth", String(n));
  render({ keepScroll: true });
}

function readingOrder() {
  return state.domains.flatMap((d) => d.topics.map((t) => `topic/${t.id}`))
    .concat(state.problems.map((p) => `problem/${p.id}`));
}

// ---------- Feedback ----------

function openFeedback() {
  const dlg = document.getElementById("feedback");
  const where = state.current ? state.current.replace("/", ": ") : "home";
  document.getElementById("fb-context").textContent = `Includes: ${where}, website`;
  document.getElementById("fb-summary").value = "";
  document.getElementById("fb-details").value = "";
  dlg.showModal();
}

function submitFeedback(event) {
  const dlg = document.getElementById("feedback");
  if (event.submitter && event.submitter.value === "cancel") return;
  const summary = document.getElementById("fb-summary").value.trim();
  if (!summary) { event.preventDefault(); return; }
  const kind = document.querySelector('#fb-kind input:checked').value;
  const details = document.getElementById("fb-details").value;
  const where = state.current ? state.current.replace("/", ": ") : "home";
  const url = new URL(`${REPO_URL}/issues/new`);
  url.searchParams.set("title", `[${kind}] ${summary}`);
  url.searchParams.set("body", `${details}\n\n---\nWhere: ${where}\nFrom: website`);
  window.open(url.toString(), "_blank", "noopener");
  dlg.close();
}

// ---------- Wiring ----------

function closeDrawer() {
  document.getElementById("sidebar").classList.remove("open");
  document.getElementById("scrim").hidden = true;
}

function wire() {
  let lastRoute = parseRoute(), goingBack = false;
  window.addEventListener("hashchange", () => {
    if (!goingBack) state.history.push(lastRoute);
    goingBack = false;
    lastRoute = parseRoute();
    render();
    closeDrawer();
  });
  document.getElementById("back-btn").addEventListener("click", () => {
    if (!state.history.length) return;
    goingBack = true;
    const prev = state.history.pop();
    location.hash = prev ? `#/${prev}` : "#/";
  });

  document.querySelectorAll(".depth button").forEach((b) =>
    b.addEventListener("click", () => setDepth(Number(b.dataset.depth))));

  document.getElementById("content").addEventListener("click", (e) => {
    const deeper = e.target.closest("[data-depth-set]");
    if (deeper) setDepth(Number(deeper.dataset.depthSet));
    const reveal = e.target.closest("[data-reveal]");
    if (reveal) { reveal.nextElementSibling.hidden = false; reveal.remove(); }
  });

  const search = document.getElementById("search");
  search.addEventListener("input", () => { state.query = search.value; renderNav(); });

  document.getElementById("nav").addEventListener("toggle", (e) => {
    const sec = e.target.closest("[data-section]");
    if (!sec || state.query) return;
    if (sec.open) state.collapsed.delete(sec.dataset.section); else state.collapsed.add(sec.dataset.section);
  }, true);

  document.getElementById("menu-btn").addEventListener("click", () => {
    document.getElementById("sidebar").classList.add("open");
    document.getElementById("scrim").hidden = false;
  });
  document.getElementById("scrim").addEventListener("click", closeDrawer);

  document.getElementById("feedback-btn").addEventListener("click", openFeedback);
  document.getElementById("feedback-form").addEventListener("submit", submitFeedback);

  // Keys: 1–4 set depth, [ goes back, j / k walk the library, / focuses search.
  document.addEventListener("keydown", (e) => {
    if (e.metaKey || e.ctrlKey || e.altKey) return;
    if (e.target.matches("input, textarea") || document.getElementById("feedback").open) return;
    if (/^[1-4]$/.test(e.key)) setDepth(Number(e.key));
    else if (e.key === "[") document.getElementById("back-btn").click();
    else if (e.key === "/") { e.preventDefault(); search.focus(); }
    else if (e.key === "j" || e.key === "k") {
      const order = readingOrder(), i = order.indexOf(state.current);
      const next = i === -1 ? order[0] : order[Math.min(Math.max(i + (e.key === "j" ? 1 : -1), 0), order.length - 1)];
      location.hash = `#/${next}`;
    }
  });
}

load()
  .then(() => { wire(); render(); })
  .catch((err) => {
    document.getElementById("content").innerHTML =
      `<div class="column"><h1>Couldn’t load content</h1><p class="muted">${escapeHTML(err.message)}</p></div>`;
  });
